name: Tests

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: ğŸ›ï¸ Checkout
      - uses: actions/setup-node@v4
        name: ğŸŸ¢ Setup Node
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
        name: ğŸš€ Install dependencies
      - run: npm run lint
        name: ğŸ§¹ Lint
      - run: npm run format:check
        name: ğŸ’… Format check
      - run: npm test
        name: ğŸ§ª Test
      - run: npm run build
        name: ğŸ—ï¸ Build
